# Generated by Django 5.0.2 on 2024-03-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_slots_canceled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='canceled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
