# Generated by Django 2.2 on 2024-01-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salons',
            name='location_link',
        ),
    ]
