# Generated by Django 2.2 on 2024-01-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_salons_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
