# Generated by Django 5.0.2 on 2024-03-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_salons_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salons',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salons',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
